### ISSUE TITLE
Fix UI glitches

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#180]
This list is going to be updated as the testing phase go:

- [x] The "loading more..." label in scrollable list flashes
- [x] Scrolling up in a short list (contact screen with 1 contact) makes the nav tabs glitch
- [x] (only iOS) Impossible to navigate back to "Addresses" after going in the "contacts" tab. To reproduce: go back and forth between the 2 tabs. In "Addresses", scroll down. Once down, click on "contacts" in the header tab bar. Try that a few times. 
- [x] Clicking on a transaction row opens the transaction details modal but scroll the transactions list to the top

**Comment by nop33** [comment]
>  The "loading more..." label in scrollable list flashes

I believe my new PR addresses this issue, but I am not sure I managed to reproduce it properly: https://github.com/alephium/mobile-wallet/pull/185

**Comment by nop33** [comment]
>  The "loading more..." label in scrollable list flashes

Here is a way to reproduce this:
After importing a new wallet (ex: the devnet one), add a new contact and navigate to the `ContactScreen`. Since the screen is a transactions flat list, which loads the next transactions page when the end of the list is reached, it keeps trying to load the next tx page until it finds some txs that include this contact, or until all tx pages have been loaded.
